### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by Zai-Kun** [sudoAlphaX/noise-play-camera-access#1]

**Comment by sudoAlphaX** [comment]
This is an api wrapper the Noise Play Vlog Edition action camera. It supports remote access mode to control the camera. The camera creates a hotspot connection to which a mobile device connects and can control the camera using the official app.
But the app, is in short, bad. Also its been pulled out from the Google Play store.
Hence, I've been reverse engineering the app and making wrapper around the HTTP requests to control the camera
